// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDso6GQEWZ1hz8PihOSACqNcHDlLpM97CQ',
    appId: '1:699286347117:android:6da6b294d0de9aeb0ace64',
    messagingSenderId: '699286347117',
    projectId: 'photo-editor-507a0',
    storageBucket: 'photo-editor-507a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNNVibwF-zp8Yba8AiWlNUcji2-GT7oMw',
    appId: '1:699286347117:ios:1e82eeaf742d65b10ace64',
    messagingSenderId: '699286347117',
    projectId: 'photo-editor-507a0',
    storageBucket: 'photo-editor-507a0.appspot.com',
    iosClientId:
        '699286347117-3dal44ckr4cv7fpd6phnkartbt8644q5.apps.googleusercontent.com',
    iosBundleId: 'com.sillyapps.photoEditor',
  );
}
